version: '3.9'

# Define uma rede customizada para que os contêineres possam se comunicar
# usando seus nomes de serviço (ex: 'app1' pode se conectar a 'db1').
networks:
  avatar-net:
    driver: bridge

services:
  # --- NÓ 1 ---
  app1:
    build: .
    container_name: avatar-node-1
    depends_on:
      - db1
    networks:
      - avatar-net
    environment:
      - APP_SERVER_PORT=8080 # Porta interna do contêiner
      - APP_CLUSTER_PORT=5701 # Porta interna do Hazelcast
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db1:5432/avatar_db
      - SPRING_DATASOURCE_USERNAME=avatar_user
      - SPRING_DATASOURCE_PASSWORD=senha123
      # Variável para o Hazelcast descobrir os outros nós. Sua aplicação precisa ler isso.
      - HAZELCAST_MEMBERS=avatar-node-1:5701,avatar-node-2:5701,avatar-node-3:5701
    ports:
      - "8081:8080" # Expõe a porta 8080 do contêiner na porta 8081 da sua máquina
      - "5701:5701" # Expõe a porta 5701 do contêiner na porta 5701 da sua máquina

  db1:
    image: postgres:17
    container_name: postgres-node-1
    networks:
      - avatar-net
    environment:
      POSTGRES_DB: avatar_db
      POSTGRES_USER: avatar_user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432" # Expõe a porta 5432 do contêiner na porta 5433 da sua máquina
    volumes:
      - postgres_data_node1:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- NÓ 2 ---
  app2:
    build: .
    container_name: avatar-node-2
    depends_on:
      - db2
    networks:
      - avatar-net
    environment:
      - APP_SERVER_PORT=8080
      - APP_CLUSTER_PORT=5701
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2:5432/avatar_db
      - SPRING_DATASOURCE_USERNAME=avatar_user
      - SPRING_DATASOURCE_PASSWORD=senha123
      - HAZELCAST_MEMBERS=avatar-node-1:5701,avatar-node-2:5701,avatar-node-3:5701
    ports:
      - "8082:8080" # Porta 8082 da sua máquina
      - "5702:5701" # Porta 5702 da sua máquina

  db2:
    image: postgres:17
    container_name: postgres-node-2
    networks:
      - avatar-net
    environment:
      POSTGRES_DB: avatar_db
      POSTGRES_USER: avatar_user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5434:5432" # Porta 5434 da sua máquina
    volumes:
      - postgres_data_node2:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- NÓ 3 ---
  app3:
    build: .
    container_name: avatar-node-3
    depends_on:
      - db3
    networks:
      - avatar-net
    environment:
      - APP_SERVER_PORT=8080
      - APP_CLUSTER_PORT=5701
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db3:5432/avatar_db
      - SPRING_DATASOURCE_USERNAME=avatar_user
      - SPRING_DATASOURCE_PASSWORD=senha123
      - HAZELCAST_MEMBERS=avatar-node-1:5701,avatar-node-2:5701,avatar-node-3:5701
    ports:
      - "8083:8080" # Porta 8083 da sua máquina
      - "5703:5701" # Porta 5703 da sua máquina

  db3:
    image: postgres:17
    container_name: postgres-node-3
    networks:
      - avatar-net
    environment:
      POSTGRES_DB: avatar_db
      POSTGRES_USER: avatar_user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5435:5432" # Porta 5435 da sua máquina
    volumes:
      - postgres_data_node3:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data_node1:
  postgres_data_node2:
  postgres_data_node3: