version: '3.9'

# Define uma rede customizada para que os contêineres possam se comunicar
networks:
  avatar-net:
    driver: bridge

services:
  # --- NÓ 1 ---
  app1:
    build: .
    container_name: avatar-node-1
    depends_on:
      - db1
    networks:
      - avatar-net
    environment:
      - APP_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db1:5432/avatar_db
      - SPRING_DATASOURCE_USERNAME=avatar_user
      - SPRING_DATASOURCE_PASSWORD=senha123
      - NODE_NAME=node-1
    ports:
      - "8081:8080"

  db1:
    image: postgres:17
    container_name: postgres-node-1
    networks:
      - avatar-net
    environment:
      POSTGRES_DB: avatar_db
      POSTGRES_USER: avatar_user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_node1:/var/lib/postgresql/data

  # --- NÓ 2 ---
  app2:
    build: .
    container_name: avatar-node-2
    depends_on:
      - db2
    networks:
      - avatar-net
    environment:
      - APP_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2:5432/avatar_db
      - SPRING_DATASOURCE_USERNAME=avatar_user
      - SPRING_DATASOURCE_PASSWORD=senha123
      - NODE_NAME=node-2
    ports:
      - "8082:8080"

  db2:
    image: postgres:17
    container_name: postgres-node-2
    networks:
      - avatar-net
    environment:
      POSTGRES_DB: avatar_db
      POSTGRES_USER: avatar_user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_node2:/var/lib/postgresql/data

  # --- NÓ 3 ---
  app3:
    build: .
    container_name: avatar-node-3
    depends_on:
      - db3
    networks:
      - avatar-net
    environment:
      - APP_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db3:5432/avatar_db
      - SPRING_DATASOURCE_USERNAME=avatar_user
      - SPRING_DATASOURCE_PASSWORD=senha123
      - NODE_NAME=node-3
    ports:
      - "8083:8080"

  db3:
    image: postgres:17
    container_name: postgres-node-3
    networks:
      - avatar-net
    environment:
      POSTGRES_DB: avatar_db
      POSTGRES_USER: avatar_user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_node3:/var/lib/postgresql/data

volumes:
  postgres_data_node1:
  postgres_data_node2:
  postgres_data_node3: