version: '3.9'

services:
  app:
    build: .
    container_name: avatar-node
    environment:
      - APP_CLUSTER_PORT=5701
      - APP_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/avatar_db
      - SPRING_DATASOURCE_USERNAME=avatar_user
      - SPRING_DATASOURCE_PASSWORD=senha123
#      Alterar para o IP da máquina que irá executar o docker-compose
#      - HAZELCAST_NETWORK_PUBLIC_ADDRESS=10.0.0.151:5701
    network_mode: host
    ports:
      - "8080:8080"
      - "5701:5701"

  db:
    image: postgres:17
    container_name: postgres-node
    environment:
      POSTGRES_DB: avatar_db
      POSTGRES_USER: avatar_user
      POSTGRES_PASSWORD: senha123
    network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_node:/var/lib/postgresql/data

volumes:
  postgres_data_node: