version: '3.9'

services:
  app1:
    build: .
    container_name: app1
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/avatar_db
      SPRING_DATASOURCE_USERNAME: avatar_user
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_FLYWAY_DEFAULT_SCHEMA: avatar_schema
    network_mode: host
    ports:
      - "8080:8080"

  db:
    image: postgres:17
    container_name: avatar-postgres
    environment:
      POSTGRES_DB: avatar_db
      POSTGRES_USER: avatar_user
      POSTGRES_PASSWORD: senha123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host
    ports:
      - "5432:5432"

volumes:
  postgres_data: