version: '3.9'

services:
  app:
    build: .
    container_name: avatar-node
    environment:
      - APP_NODE_ID=node-1x
      - APP_CLUSTER_PORT=5701
      - APP_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql:db:5432/avatar_node
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - HAZELCAST_NETWORK_PUBLIC_ADDRESS=172.16.201.x:5701
    network_mode: host
    ports:
      - "8080:8080"
      - "5701:5701"

  db:
    image: postgres:17
    container_name: postgres-node
    environment:
      POSTGRES_DB: avatar_node
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_node1:/var/lib/postgresql/data

volumes:
  postgres_data_node1: