version: '3.9'

services:
  db:
    image: postgres:17
    container_name: postgres-node
    environment:
      POSTGRES_DB: avatar_db
      POSTGRES_USER: avatar_user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_node:/var/lib/postgresql/data
    networks:
      - avatar-network

  app:
    build: .
    container_name: avatar-node
    depends_on:
      - db
    environment:
      - APP_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/avatar_db
      - SPRING_DATASOURCE_USERNAME=avatar_user
      - SPRING_DATASOURCE_PASSWORD=senha123

    network_mode: host

networks:
  avatar-network:
    driver: bridge

volumes:
  postgres_data_node: